name: Publish Extension

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run compile

    - name: Package (create vsix)
      run: npx @vscode/vsce package --yarn --no-dependencies -o ./extension.vsix

    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: ./extension.vsix

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-vsix
        path: ./extension.vsix
